title: Bodhi McNally
#logo: /assets/img/headshot_circle.png
description: Key Account Manager @ AbbVie/DKSH Healthcare | Patient Engagement & Sales Strategy Expert | Data-Driven Problem Solver | Worked on Novo Nordisk, Roche & AbbVie Projects
#show_downloads: true
theme: jekyll-theme-minimal
