title: Bodhi McNally
#logo: /assets/img/headshot_circle.png
description: Hi, I’m Bodhi, a Key Account Manager for AbbVie at DKSH Healthcare Australia. I’m passionate about patient engagement, sales strategy and solving tough problems with data. I’ve worked on projects with Novo Nordisk, Roche and AbbVie, and love turning insights into impact.
#show_downloads: true
theme: jekyll-theme-minimal
