title: Bodhi McNally
logo: /assets/img/headshot_circle.png
description: Hi, I’m Bodhi, a Doctor of Medicine student at the University of Sydney with a background in data science and genetics. I’m interested in applying quantitative methods to clinical work, research and healthcare systems, with experience across healthcare analytics, primary care engagement and education.
#show_downloads: true
theme: jekyll-theme-minimal
